name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Make 1GB file
        run: | 
          dd if=/dev/zero of=file.img bs=1G count=1
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file.img
          path: file.img
      - name: Delete 1GB file
        run: rm -rf file.img

      - name: Make 2GB file
        run: |
          dd if=/dev/zero of=file.img bs=2G count=1
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file.img
          path: file.img
      - name: Delete 2GB file
        run: rm -rf file.img

      - name: Make 3GB file
        run: |
          dd if=/dev/zero of=file.img bs=3G count=1
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file.img
          path: file.img
      - name: Delete 3GB file
        run: rm -rf file.img

      - name: Make 4GB file
        run: |
          dd if=/dev/zero of=file.img bs=4G count=1
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file.img
          path: file.img
      - name: Delete 4GB file
        run: rm -rf file.img

      - name: Make 5GB file
        run: |
          dd if=/dev/zero of=file.img bs=1G count=1
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file.img
          path: file.img
      - name: Delete 5GB file
        run: rm -rf file.img