name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install and run YouTube-DL
        run: |
          curl -LJO https://github.com/ytdl-org/youtube-dl/releases/latest/download/youtube-dl
          chmod +x ./youtube-dl
          sudo ./youtube-dl --config-location youtube-dl.conf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: downloads
          path: downloads
