name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Make 1GB file
        run: | 
          mkdir folder
          dd if=/dev/zero of=folder/1g.img count=1024 bs=1M
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 1g
          path: folder
      - name: Delete 1GB file
        run: rm -rf *

      - name: Make 2GB file
        run: |
          dd if=/dev/zero of=folder/2g.img count=1024 bs=2M
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 2g
          path: folder
      - name: Delete 2GB file
        run: rm -rf *

      - name: Make 3GB file
        run: |
          dd if=/dev/zero of=folder/3g.img count=1024 bs=3M
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 3g
          path: folder
      - name: Delete 3GB file
        run: rm -rf *

      - name: Make 4GB file
        run: |
          dd if=/dev/zero of=folder/4g.img count=1024 bs=4M
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 4g
          path: folder
      - name: Delete 4GB file
        run: rm -rf *

      - name: Make 5GB file
        run: |
          dd if=/dev/zero of=folder/5g.img count=1024 bs=5M
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 5g
          path: folder
      - name: Delete 5GB file
        run: rm -rf *